name: Validate Practica 1 (2021)

on:
  pull_request:
    paths:
      - 'practicas/2021.practica1/**'

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install tools
      run: |
        cmake --version
        python --version
        python -m pip install --upgrade pip
        python -m pip install conan
        conan --version
        conan config init
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan profile show default

    - name: Compile
      run: |
        mkdir _build && cd _build
        conan install ../practicas/2021.practica1/conanfile.txt -s build_type=Release
        cmake ../practicas/2021.practica1 -DCMAKE_MODULE_PATH=$(pwd)
        cmake --build .

    - name: Run tests
      working-directory: _build
      run: |
        ./unit_tests
